# Generated by Django 2.1.5 on 2019-07-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='01000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.BooleanField(default=True),
        ),
    ]
