# Generated by Django 2.1.5 on 2019-09-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190728_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nameUser',
            field=models.CharField(default='이름이름', max_length=20),
        ),
    ]
