# Generated by Django 2.2.3 on 2019-07-28 05:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAgeORM',
            fields=[
                ('child_age_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'child_age',
            },
        ),
        migrations.CreateModel(
            name='JobAgeORM',
            fields=[
                ('job_age_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(help_text='지원 연령대')),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'job_age',
            },
        ),
        migrations.CreateModel(
            name='JobCarPreferenceORM',
            fields=[
                ('car_preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', help_text='차량소지선호 여부', max_length=20)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'job_car_preference',
            },
        ),
        migrations.CreateModel(
            name='JobDayOfWeekORM',
            fields=[
                ('jog_day_of_week_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=5)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'job_day_of_week',
            },
        ),
        migrations.CreateModel(
            name='JobSexORM',
            fields=[
                ('job_sex_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(default='', help_text='성별', max_length=10)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'job_sex',
            },
        ),
        migrations.CreateModel(
            name='JobORM',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=0, help_text='회원 번호')),
                ('status', models.SmallIntegerField(default=1)),
                ('title', models.CharField(default='', help_text='글 제목', max_length=50)),
                ('pay', models.IntegerField(default=0)),
                ('is_negotiation', models.BooleanField(default=False)),
                ('location_id', models.SmallIntegerField(default=1)),
                ('sub_location_id', models.SmallIntegerField(default=1)),
                ('third_location_id', models.SmallIntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('start_available_calling_time', models.SmallIntegerField(default=9)),
                ('end_available_calling_time', models.SmallIntegerField(default=18)),
                ('start_working_time', models.SmallIntegerField(null=True)),
                ('end_working_time', models.SmallIntegerField(null=True)),
                ('start_working_date', models.DateField(default=django.utils.timezone.now)),
                ('end_working_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('car_preference_id', models.ForeignKey(db_column='car_preference_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_preference', to='job.JobCarPreferenceORM')),
                ('child_age_id', models.ForeignKey(db_column='child_age_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_age', to='job.ChildAgeORM')),
                ('worker_age_from_id', models.ForeignKey(db_column='worker_age_from_id', help_text='지원 연령대 시작', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_age_from', to='job.JobAgeORM')),
                ('worker_age_to_id', models.ForeignKey(db_column='worker_age_to_id', help_text='지원 연령대 끝', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_age_to', to='job.JobAgeORM')),
                ('worker_sex_id', models.ForeignKey(db_column='worker_sex_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_sex', to='job.JobSexORM')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobDayOfWeekMappingORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.BigIntegerField()),
                ('day_of_week_id', models.ForeignKey(db_column='day_of_week_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobDayOfWeekORM')),
            ],
            options={
                'db_table': 'job_day_of_week_mapping',
            },
        ),
    ]
