# Generated by Django 2.2.3 on 2019-07-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdayofweekorm',
            old_name='jog_day_of_week_id',
            new_name='job_day_of_week_id',
        ),
        migrations.AlterField(
            model_name='jobdayofweekmappingorm',
            name='day_of_week_id',
            field=models.ForeignKey(db_column='day_of_week_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobDayOfWeekORM', to_field='jog_day_of_week_id'),
        ),
    ]
