# Generated by Django 2.2.3 on 2019-10-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190728_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocationORM',
            fields=[
                ('job_location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_location_id', models.IntegerField(null=True)),
                ('depth', models.SmallIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'job_location',
            },
        ),
        migrations.CreateModel(
            name='JobRequireDocumentORM',
            fields=[
                ('job_require_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'job_require_document',
            },
        ),
        migrations.RemoveField(
            model_name='joborm',
            name='car_preference_id',
        ),
        migrations.AddField(
            model_name='joborm',
            name='car_preference',
            field=models.ForeignKey(db_column='car_preference_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobCarPreferenceORM'),
        ),
        migrations.AddField(
            model_name='joborm',
            name='day_of_weeks',
            field=models.ManyToManyField(null=True, related_name='day_of_weeks', through='job.JobDayOfWeekMappingORM', to='job.JobDayOfWeekORM'),
        ),
        migrations.AlterField(
            model_name='jobdayofweekmappingorm',
            name='day_of_week_id',
            field=models.ForeignKey(db_column='day_of_week_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobDayOfWeekORM'),
        ),
        migrations.AlterField(
            model_name='jobdayofweekmappingorm',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='job.JobORM'),
        ),
        migrations.AlterField(
            model_name='joborm',
            name='end_available_calling_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='joborm',
            name='end_working_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='joborm',
            name='start_available_calling_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='joborm',
            name='start_working_time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='JobRequireDocumentMappingORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.BigIntegerField()),
                ('require_document_id', models.ForeignKey(db_column='job_require_document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobRequireDocumentORM')),
            ],
            options={
                'db_table': 'job_require_document_mapping',
            },
        ),
    ]
