# Generated by Django 2.2.3 on 2019-10-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20191020_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joborm',
            old_name='child_age_id',
            new_name='child_age',
        ),
        migrations.RenameField(
            model_name='joborm',
            old_name='worker_age_from_id',
            new_name='worker_age_from',
        ),
        migrations.RenameField(
            model_name='joborm',
            old_name='worker_age_to_id',
            new_name='worker_age_to',
        ),
        migrations.RenameField(
            model_name='joborm',
            old_name='worker_sex_id',
            new_name='worker_sex',
        ),
        migrations.AddField(
            model_name='joborm',
            name='documents',
            field=models.ManyToManyField(null=True, related_name='documents', through='job.JobRequireDocumentMappingORM', to='job.JobRequireDocumentORM'),
        ),
        migrations.AlterField(
            model_name='jobrequiredocumentmappingorm',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='job.JobORM'),
        ),
    ]
