# Generated by Django 2.2.3 on 2019-10-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20191020_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborm',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='joborm',
            name='sub_location_id',
        ),
        migrations.AddField(
            model_name='joborm',
            name='root_location',
            field=models.ForeignKey(db_column='root_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_location', to='job.JobLocationORM'),
        ),
        migrations.AddField(
            model_name='joborm',
            name='second_location',
            field=models.ForeignKey(db_column='second_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_location', to='job.JobLocationORM'),
        ),
    ]
