# Generated by Django 2.2.3 on 2019-12-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20191020_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborm',
            name='worker_age_from',
        ),
        migrations.RemoveField(
            model_name='joborm',
            name='worker_age_to',
        ),
        migrations.CreateModel(
            name='JobAgeMappingORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_id', models.ForeignKey(db_column='job_age_id', on_delete=django.db.models.deletion.CASCADE, to='job.JobAgeORM')),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='job.JobORM')),
            ],
            options={
                'db_table': 'job_age_mapping',
            },
        ),
        migrations.AddField(
            model_name='joborm',
            name='worker_age',
            field=models.ManyToManyField(null=True, related_name='worker_age', through='job.JobAgeMappingORM', to='job.JobAgeORM'),
        ),
    ]
